name: Patch Allure Base Path on Push

on:
  push:
    branches: [ main ]

jobs:
  patch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Inject base href for subpath hosting
        run: |
          sed -i 's|<head>|<head><base href="/allure-reports/" />|' ./docs/index.html

      - name: Commit patched index.html
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add ./docs/index.html
          git commit -m "Patch base href for GitHub Pages" || echo "No changes to commit"
          git push
