name: Deploy Allure Report

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate Allure Report
        run: |
          # Make sure allure command is available; if not, install allure CLI
          # Generate report assuming test results in ./allure-results
          allure generate ./allure-results --clean -o ./docs

      - name: Fix Base URL for GitHub Pages
        run: |
          sed -i 's|<head>|<head><base href="/allure-reports/" />|' ./docs/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
